name: pipeline

on: 
  push:
    branches:
      - 'master'
      - 'develop'
  pull_request:

jobs:
  pipeline:
    name: pipeline
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      - name: Build project
        run: mvn -B clean compile

      - name: Test
        run: mvn -B clean verify

  sonarqube:
    name: sonarqube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      - name: SonarQube
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify sonar:sonar -Psonar -Pcoverage -Dsonar.login=${{ SECRETS.SONAR_TOKEN }}
